import time
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

# List of songs
# List of songs
songs = [
    "12-BAR-BLUES-LIST",
    "A-DAISY-A-DAY",
    "A-KIND-OF-HUSH-1",
    "A-Kiss-to-Build-a-Dream-On_Songsheet",
    "A-WHITE-SPORT-COAT-final",
    "A-WORRIED-MAN-KingstonTrio-Original-Key",
    "A-WORRIED-MAN-KingstonTrio",
    "ABILENE",
    "ABILENE-F",
    "AINT-SHE-SWEET",
    "ALL-FOR-THE-LOVE-OF-A-GIRL",
    "ALL-I-HAVE-TO-DO-IS-DREAM",
    "ALL-MY-LOVING",
    "ALL-OF-ME-easy",
    "AMARILLO-BY-MORNING",
    "ARE-YOU-LONESOME-TONIGHT",
    "Act-Naturally",
    "BACK-HOME-AGAIN",
    "BAD-BAD-LEROY-BROWN-Revised-Feb-2023",
    "BAD-MOON-RISING",
    "BALLAD-OF-JED-CLAMPETT",
    "BALLAD-OF-JED-CLAMPETT",
    "BEAUTIFUL-BROWN-EYES",
    "BEAUTIFUL-SUNDAY",
    "BIG-ROCK-CANDY-MOUNTAIN",
    "BLAME-IT-ON-THE-UKULELE",
    "BLOWIN-In-The-Wind-in-G",
    "BLUE-BAYOU",
    "BLUE-BLUE-DAY",
    "BLUE-CANADIAN-ROCKIES",
    "BLUE-EYES-CRYING-IN-THE-RAIN-easy",
    "BLUE-EYES-CRYING-IN-THE-RAIN-hard",
    "BLUE-HAWAII",
    "BLUE-MOON-HEART-SOUL-MEDLEY",
    "BLUE-SKIES-Am",
    "BLUE-SKIES-with-tabs-Am",
    "BLUES-STAY-AWAY-FROM-ME",
    "BRAND-NEW-KEY",
    "BRAND-NEW-KEY",
    "BRAND-NEW-KEY",
    "BRING-IT-ON-DOWN-TO-MY-HOUSE-D",
    "BUFFALO-GALS",
    "BUTTONS-AND-BOWS",
    "BYE-BYE-LOVE",
    "CALIFORNIA-BLUES",
    "CANT-HELP-BUT-SMILE",
    "CHANTILLY-LACE-D",
    "CHICKEN-WIRE-G",
    "CIRCLE-A",
    "CITY-OF-NEW-ORLEANS",
    "COTTON-FIELDS",
    "COULD-I-HAVE-THIS-DANCE",
    "CRAWDAD-SONG",
    "CROCODILE-ROCK-C",
    "DA-DOO-RON-RON",
    "DEAR-HEARTS-AND-GENTLE-PEOPLE",
    "DID-SHE-MENTION-MY-NAME",
    "DIFFERENT-DRUM",
    "DONALD-WHERES-YOUR-TROOSERS-Am",
    "DONT-BE-CRUEL",
    "DONT-FENCE-ME",
    "DONT-LET-THE-OLD-MAN-IN",
    "DONT-THINK-TWICE",
    "DONT-WORRY-BE-HAPPY",
    "DOWN-IN-THE-VALLEY-dr",
    "DOWN-IN-THE-VALLEY-with-timing",
    "DOWN-ON-THE-CORNER",
    "DREAM-BABY",
    "DRUNKEN-SAILOR-Am",
    "EARLY-MORNING-RAIN",
    "EIGHT-DAYS-A-WEEK",
    "ELVIRA",
    "END-OF-THE-LINE-D",
    "EVERYBODY-LOVES-A-LOVER-D-easy",
    "EVERYBODY-LOVES-A-LOVER-F-More-difficult",
    "FIELDS-OF-GOLD",
    "FIVE-FOOT-TWO",
    "FIVE-FOOT-TWO",
    "FIVE-HUNDRED-MILES",
    "FLIP-FLOP-AND-FLY",
    "FLY-ME-TO-THE-MOON",
    "FOR-THE-GOOD-TIMES",
    "FOUR-STRONG-WINDS",
    "FRAULEIN",
    "FRIENDS-LIKE-YOU-A",
    "FRIENDS-LIKE-YOU",
    "GAMBLER-THE",
    "GEISHA-GIRL",
    "GEORGIA-ON-MY-MIND_C",
    "GIRL-CRUSH",
    "GOING-DOWN-TO-THE-RIVER",
    "GOOD-HEARTED-WOMAN-CD",
    "GOOD-HEARTED-WOMAN-DE",
    "GOOD-LUCK-CHARM",
    "GOODNIGHT-IRENE",
    "GOODNIGHT-IRENE",
    "GOTTA-TRAVEL-ON",
    "GREEN-DOOR_A",
    "GUESS-THINGS-HAPPEN-THAT-WAY",
    "HAPPY-BIRTHDAY-SONG",
    "HARPER-VALLEY-P.T.A.-GA",
    "HAVE-I-TOLD-YOU-LATELY",
    "HAVE-YOU-EVER-SEEN-THE-RAIN",
    "HEART-OF-MY-HEART-F",
    "HELLO-MARY-LOU",
    "HELP-ME-MAKE-IT-THROUGH-THE-NIGHT-A-easy",
    "HELP-ME-MAKE-IT-THROUGH-THE-NIGHT-G-hard",
    "HEY-GOOD-LOOKIN",
    "HEY-GOOD-LOOKIN-IN",
    "HOBOS-LULLABY",
    "HOUSE-OF-THE-RISING-SUN-Am",
    "HOW-MUCH-IS....-DOGGIE",
    "I-CAN-HELP",
    "I-CAN-SEE-CLEARLY-NOW",
    "I-CANT-HELP-FALLING-IN-LOVE-WITH-YOU",
    "I-HAVE-A-DREAM-A",
    "I-HAVE-A-DREAM",
    "I-KNOW",
    "I-LOVE-HOW-YOU-LOVE-ME-in-C",
    "I-Love-Onions",
    "I-OVERLOOKED-AN-ORCHID",
    "ID-LIKE-TO-TEACH",
    "IF-I-HAD-A-HAMMER-hard",
    "IF-I-NEEDED-YOU-REVISED",
    "IKO-IKO-1",
    "IM-SO-LONESOME-I-COULD-CRY",
    "IM-SORRY",
    "ISE-THE-BYS",
    "IT-AINT-ME-BABE",
    "IT-DOESNT-MATTER-ANYMORE",
    "IVE-JUST-SEEN-A-FACE",
    "JAMAICA-FAREWELL",
    "JAMBALAYA",
    "JAMBALAYA",
    "KANSAS-CITY",
    "KENTUCKY-WALTZ",
    "KENTUCKY-WALTZ",
    "KENTUCKY-WALTZ",
    "KING-OF-THE-ROAD",
    "King-of-the-Road-Harmony",
    "LAST-THING-ON-MY-MIND",
    "LEAVING-ON-A-JET-PLANE",
    "LET-IT-BE-ME-Cshort",
    "LET-IT-BE-ME-F-long",
    "LET-IT-BE-ME-F-short",
    "LET-IT-BE-ME-G-long",
    "LET-THE-REST-OF-THE-WORLD-GO-BY-F",
    "LETS-TWIST-AGAIN",
    "LION-SLEEPS-TONIGHT",
    "LOG-DRIVERS-WALTZ",
    "LONG-TALL-TEXAN",
    "LOVIN-YOU",
    "LYIN-EYES_C",
    "Love-Potion-9-Am",
    "MAKE-THE-WORLD-GO-AWAY",
    "MAMA-DONT-ALLOW",
    "MAMAS-DONT-LET...COWBOYS",
    "MAN-OF-CONSTANT-SORROW_C",
    "MARGARITAVILLE",
    "MARIANNE",
    "ME-BOBBY-MCGEE-G-A-",
    "MICHAEL-ROW-THE-BOAT-CD",
    "MOCKINGBIRD-HILL",
    "MOVE-IT-ON-OVER-A",
    "MOVE-IT-ON-OVER",
    "MY-HAPPINESS-F",
    "MY-SHOES-KEEP-WALKING..G",
    "NOBODYS-DARLIN-BUT-MINE_G",
    "OCTOPUSS-GARDEN",
    "OH-LONESOME-ME-C",
    "OH-LONESOME-ME-G",
    "OLD-IRA-CD",
    "ON-THE-ROAD-AGAIN_C",
    "ON-THE-WINGS",
    "ONE-DAY-AT-A-TIME",
    "PEACEFUL-EASY-FEELING",
    "PEARLY-SHELLS",
    "PLAY-A-SIMPLE-MELODY",
    "PUT-A-LITTLE-LOVE",
    "PUT-YOUR-HAND-IN-THE-HAND",
    "RED-RIVER-VALLEY",
    "RED-RIVER-VALLEY",
    "RED-RIVER-VALLEY",
    "RHUMBA-MAN",
    "RIDER-IN-THE-RAIN",
    "RIPPLE",
    "RIVER-ROAD",
    "RUNAROUND-STU-IN-C",
    "RUNAWAY",
    "RV",
    "SAILING",
    "SAVE-THE-LAST-DANCE-FOR-ME",
    "SEA-CRUISE",
    "SEND-ME-THE-PILLOW",
    "SILHOUETTES",
    "SILHOUETTES",
    "SILHOUETTES",
    "SIMPLE-SONG-OF-FREEDOM",
    "SINGIN-THE-BLUES",
    "SIXTEEN-TONS",
    "SKYE-BOAT-SONG",
    "SLOW-POKE",
    "SOMETHING-IN-RED",
    "SONG-FOR-A-WINTERS-NIGHT",
    "SONG-FOR-THE-MIRA",
    "SONNYS-DREAM",
    "ST.-JAMES-INFIRMARY",
    "STAND-BY-ME",
    "STRUM-A-UKULELE",
    "SUMMER-WAGES",
    "SWAY",
    "SWEET-GEORGIA-BROWN-Revised-Feb-2023",
    "TAKE-ME-HOME-COUNTRY-ROADS",
    "TALK-BACK-TREMBLING-LIPS",
    "TENNESSEE-WALTZ",
    "THATS-MY-WEAKNESS-NOW",
    "THE-HOCKEY-SONG",
    "THERE-IS-A-TAVERN",
    "THERE-IS-A-TAVERN",
    "THESE-BOOTS",
    "THIS-LAND-IS-YOUR-LAND",
    "THREE-LITTLE-BIRDS",
    "TINY-BUBBLES",
    "TO-LOVE-SOMEBODY-D",
    "TOM-DOOLEY",
    "TRY-A-LITTLE-KINDNESS",
    "TRY-TO-REMEMBER",
    "TULSA-TIME",
    "TWENTY-SIX-MILES",
    "UKULELE-LADY",
    "UKULELE-LADY",
    "UKULELE-LADY",
    "UNDER-THE-BOARDWALK",
    "UP-ABOVE-MY-HEAD",
    "WABASH-CANNONBALL",
    "WAGON-WHEEL-KAMLOOPS",
    "WALKIN-AFTER-MIDNIGHT",
    "WALKIN-AFTER-MIDNIGHT",
    "WALKING-THE-FLOOR-OVER-YOU",
    "WALTZ-ACROSS-TEXAS_D",
    "WALTZING-MATILDA",
    "WAYFARING-STRANGER",
    "WAYWARD-WIND-THE",
    "WELL-MEET-AGAIN-F",
    "WELL-SING-IN-THE-SUNSHINE",
    "WELLERMAN-THE",
    "WHEN-MY-BLUE-MOON-TURNS-TO-GOLD-AGAIN-D",
    "WHEN-THE-RED-RED-ROBIN",
    "WHERE-THE-COHO-FLASH-SILVER",
    "WHISKEY-IN-THE-JAR",
    "WHISPERING-PINES",
    "WHISPERING-PINES",
    "WHOLL-STOP-THE-RAIN",
    "WILL-THE-CIRCLE-BE-UNBROKEN_C_to_D",
    "WOLVERTON-MOUNTAIN",
    "WORKING-MAN",
    "WORRIED-MAN-A-in-D",
    "YOU-ARE-MY-SUNSHINE",
    "YOU-WONT-SEE-ME",
    "YOUR-CHEATING-HEART",
    "YOURE-NOBODY-TIL...",
    "YOURE-SIXTEEN",
    "YOUVE-GOT-A-FRIEND"
]

# Your email and password for YouTube Music
email = "amlannag6@gmail.com"
password = "Manik240206@"

# Initialize the web driver (assuming you have ChromeDriver installed)
driver = webdriver.Chrome(executable_path="path/to/chromedriver")

# Open YouTube Music
driver.get("https://music.youtube.com/")

# Wait for the page to load
time.sleep(5)

# Click on the "Sign in" button
sign_in_button = driver.find_element_by_xpath("//span[text()='Sign in']")
sign_in_button.click()

# Enter your email and click "Next"
email_input = driver.find_element_by_name("identifier")
email_input.send_keys(email)
email_input.send_keys(Keys.RETURN)

# Wait for the password input field to appear
time.sleep(5)

# Enter your password and click "Next"
password_input = driver.find_element_by_name("password")
password_input.send_keys(password)
password_input.send_keys(Keys.RETURN)

# Wait for the YouTube Music homepage to load
time.sleep(10)

# Loop through the list of songs and search/add them to your library
for song in songs:
    search_box = driver.find_element_by_xpath("//input[@aria-label='Search']")
    search_box.clear()
    search_box.send_keys(song)
    search_box.send_keys(Keys.RETURN)

    # Wait for search results to load
    time.sleep(5)

    # Click on the first search result to add the song to your library
    add_button = driver.find_element_by_xpath("//div[@title='Add to library']")
    add_button.click()

    # Wait for the song to be added
    time.sleep(5)

# Close the web driver
driver.quit()